name: Laravel

on:
  push:
    branches: [ * ]
  pull_request:
    branches: [ * ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: composer test

  php-cs-Fixer:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: PHP-CS-Fixer
      uses: docker://oskarstark/php-cs-fixer-ga
      with:
        args: --config=.php-cs-fixer.dist.php --allow-risky=yes

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v2.3.0
      with:
          commit_message: Fix styling
          branch: ${{ steps.extract_branch.outputs.branch }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
